### ISSUE TITLE
Error in LSRegisterURL: -10811

### ISSUE THREAD

**Issue by ScuroNeko** [MinnDevelopment/Java-DiscordRPC#33] opened 2018-12-17 20:28 UTC
I use follow code

```java
import club.minnced.discord.rpc.*;

public class Main {
    public static void main(String[] args) {
        DiscordRPC lib = DiscordRPC.INSTANCE;
        String applicationId = "";
        String steamId = "";
        DiscordEventHandlers handlers = new DiscordEventHandlers();
        handlers.ready = (user) -> System.out.println("Ready!");
        lib.Discord_Initialize(applicationId, handlers, true, steamId);
        DiscordRichPresence presence = new DiscordRichPresence();
        presence.startTimestamp = System.currentTimeMillis() / 1000; // epoch second
        presence.details = "Testing RPC";
        lib.Discord_UpdatePresence(presence);
        new Thread(() -> {
            while (!Thread.currentThread().isInterrupted()) {
                lib.Discord_RunCallbacks();
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ignored) {}
            }
        }, "RPC-Callback-Handler").start();
    }
}
```

and i get error in log
`Error in LSRegisterURL: -10811`

**Comment by MinnDevelopment** [comment] 2018-12-17 21:03
This is a duplicate of https://github.com/discordapp/discord-rpc/issues/170

**Closed as completed by MinnDevelopment** 2018-12-17 21:03 UTC
Labels: level: native
