### ISSUE TITLE
Handlers not being triggered

### ISSUE THREAD

**Issue by Timeraa** [MinnDevelopment/Java-DiscordRPC#29] opened 2018-08-15 04:25 UTC
Hey,

So i already set up the presence etc everything works, but how do i catch an error/check if discord is even running?

**Comment by MinnDevelopment** [comment] 2018-08-15 12:16
You can use the event handlers you pass to `Discord_Initialize` to determine when it connects or disconnects.

**Comment by Timeraa** [comment] 2018-08-16 04:36
Okay so after some testing i got the Ready event to work but every other event is not working...

```JAVA
        handlers.errored = (err, err1) -> {
            System.out.println(err + "\n" + err1);
        };
        handlers.disconnected = (err, err1) -> {
            System.out.println(err + "\n" + err1);
        };
        handlers.ready = (user) -> {
            System.out.print(user);
        };
```

This is the code i am using for the events. I added it under the handlers declaration (initPresence())

if you want the full class (Note the events are not included):
[here](https://github.com/MCDiamondFire/DiamondFireUtilities/blob/master/src/main/java/dfutils/utils/rpc/PresenceHandler.java)

**Comment by MinnDevelopment** [comment] 2018-08-16 12:43
Handlers not being triggered can only be caused by the official SDK. This seems related to discordapp/discord-rpc#220

**Comment by Timeraa** [comment] 2018-08-16 22:14
I am using it on MacOS and i get this famous LRegistry error. Maybe its related to the events not being triggered?

**Comment by MinnDevelopment** [comment] 2018-08-16 23:27
That error means it was unable to create the command used to start the app from within discord.

**Comment by MinnDevelopment** [comment] 2018-08-26 02:10
I have proposed a fix for the disconnected event handler to the official SDK, it is currently waiting to be reviewed.

**Comment by MinnDevelopment** [comment] 2018-11-27 18:06
This should be fixed in 2.0.2, feel free to open a new issue for other complications.

**Closed as completed by MinnDevelopment** 2018-11-27 18:06 UTC
Labels: bug, level: native
