### ISSUE TITLE
Error in LSRegisterURL: -10811

### ISSUE THREAD

**Issue by Mimmob07** [MinnDevelopment/Java-DiscordRPC#43] opened 2021-04-04 17:00 UTC
whenever i try to start the discord rpc it gives me this error
```
Error in LSRegisterURL: -10811
```
does anyone know how to fix this?
(I'm on macos/darwin)

**Comment by MinnDevelopment** [comment] 2021-04-04 19:24
Duplicate of #33

**Closed as completed by MinnDevelopment** 2021-04-04 19:24 UTC
