### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc'

### ISSUE THREAD

**Issue by C21H30O3** [MinnDevelopment/Java-DiscordRPC#44] opened 2021-08-26 11:50 UTC
java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc'

**Comment by shabman** [comment] 2021-09-11 10:21
getting same issue too

**Comment by MinnDevelopment** [comment] 2021-10-02 15:54
Duplicate of #30 

This issue is with your setup, and you need to resolve it yourself. This library depends on a specific version of JNA and a transitive dependency [discord-rpc-release](https://github.com/MinnDevelopment/discord-rpc-release). It is highly recommended using this library with maven or gradle exclusively.

**Closed as completed by MinnDevelopment** 2021-10-02 15:54 UTC
